AWSTemplateFormatVersion: '2010-09-09'
Description: Stack para subir novo ECS Cluster speech-ai-hml-front-ecs
Parameters: {}
Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: speech-ai-hml-front-ecs
      ClusterSettings:
        - Name: containerInsights
          Value: disabled
      Configuration:
        ManagedStorageConfiguration:
          KmsKeyId: arn:aws:kms:us-east-1:676206949005:key/6ed194c5-d0f0-4a21-96e5-93749d1b0686
      ServiceConnectDefaults:
        Namespace: arn:aws:servicediscovery:us-east-1:676206949005:namespace/ns-xbgssk4zhosioqjx

  ECSLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: !Sub "{{resolve:ssm:/aws/service/ecs/optimized-ami/amazon-linux-2/kernel-5.10/recommended/image_id}}"
        SecurityGroupIds:
          - sg-0d1f0c8aaf072faab
          - sg-0156472c6f16569a9
        InstanceType: t2.large
        KeyName: ecs-key
        IamInstanceProfile:
          Arn: arn:aws:iam::676206949005:instance-profile/ecsInstanceRole
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              VolumeSize: 30
        UserData:
          Fn::Base64: |
            #!/bin/bash
            echo ECS_CLUSTER=speech-ai-hml-front-ecs >> /etc/ecs/ecs.config

  ECSAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MinSize: '1'
      MaxSize: '1'
      DesiredCapacity: '1'
      LaunchTemplate:
        LaunchTemplateId: !Ref ECSLaunchTemplate
        Version: !GetAtt ECSLaunchTemplate.LatestVersionNumber
      VPCZoneIdentifier:
        - subnet-0b5b18c88d776fc96
        - subnet-067c5630ff520a5d0
        - subnet-0afb7c9ff4f5977bd
      Tags:
        - Key: Name
          Value: ECS Instance speech-ai-hml-front-ecs
          PropagateAtLaunch: true

  AsgCapacityProvider:
    Type: AWS::ECS::CapacityProvider
    Properties:
      AutoScalingGroupProvider:
        AutoScalingGroupArn: !Ref ECSAutoScalingGroup
        ManagedScaling:
          Status: ENABLED
          TargetCapacity: 100
        ManagedTerminationProtection: DISABLED

  ClusterCPAssociation:
    Type: AWS::ECS::ClusterCapacityProviderAssociations
    Properties:
      Cluster: !Ref ECSCluster
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
        - !Ref AsgCapacityProvider
      DefaultCapacityProviderStrategy:
        - Base: 0
          Weight: 1
          CapacityProvider: !Ref AsgCapacityProvider

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      TaskDefinition: arn:aws:ecs:us-east-1:676206949005:task-definition/speech-ai-hml-front-td:1
      LaunchType: EC2
      ServiceName: speech-ai-hml-front-service
      SchedulingStrategy: REPLICA
      DesiredCount: 1
      HealthCheckGracePeriodSeconds: 5
      AvailabilityZoneRebalancing: ENABLED
      DeploymentConfiguration:
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      DeploymentController:
        Type: ECS
      ServiceConnectConfiguration:
        Enabled: false
      PlacementStrategies:
        - Type: spread
          Field: attribute:ecs.availability-zone
        - Type: spread
          Field: instanceId
      EnableECSManagedTags: true
      LoadBalancers:
        - TargetGroupArn: arn:aws:elasticloadbalancing:us-east-1:676206949005:targetgroup/speech-ai-hml-front-tg/f492f1edfd02ed26
          ContainerName: speech-ai-hml-front-container
          ContainerPort: 80
      Role: arn:aws:iam::676206949005:role/ecsServiceRole

Outputs:
  ClusterName:
    Value: !Ref ECSCluster
  ServiceName:
    Value: !Ref ECSService
